[theme]
base="dark"
backgroundColor="#3a1898"

Initialized tornado logs
# Below are all the sections and options you can have in ~/.streamlit/config.toml.

[global]

# By default, Streamlit checks if the Python watchdog module is available and, if not, prints a warning asking for you to install it. The watchdog module is not required,
but highly recommended. It improves Streamlit's ability to detect changes to files in your filesystem.
# If you'd like to turn off this warning, set this to True.
# Default: false
disableWatchdogWarning = false

# Configure the ability to share apps to the cloud.
# Should be set to one of these values: - "off" : turn off sharing. - "s3" : share to S3, based on the settings under the [s3] section of this config file.
# Default: "off"
sharingMode = "off"

# If True, will show a warning when you run a Streamlit-enabled script via "python my_script.py".
# Default: true
showWarningOnDirectExecution = true

# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
logLevel = "info"


[client]

# Whether to enable st.cache.
# Default: true
# The value below was set in H:\.streamlit\config.toml
caching = true

# If false, makes your Streamlit script not draw to a Streamlit app.
# Default: true
# The value below was set in H:\.streamlit\config.toml
displayEnabled = true


[runner]

# Allows you to type a variable or string by itself in a single line of Python code to write it to the app.
# Default: true
# The value below was set in H:\.streamlit\config.toml
magicEnabled = true

# Install a Python tracer to allow you to stop or pause your script at any point and introspect it. As a side-effect, this slows down your script's execution.
# Default: false
# The value below was set in H:\.streamlit\config.toml
installTracer = false

# Sets the MPLBACKEND environment variable to Agg inside Streamlit to prevent Python crashing.
# Default: true
# The value below was set in H:\.streamlit\config.toml
fixMatplotlib = true


[server]

# List of folders that should not be watched for changes. Relative paths will be taken as relative to the current working directory.
# Example: ['/home/user1/env', 'relative/path/to/folder']
# Default: []
# The value below was set in H:\.streamlit\config.toml
folderWatchBlacklist = ['\helper']

# Immediately share the app in such a way that enables live monitoring, and post-run analysis.
# Default: false
# The value below was set in H:\.streamlit\config.toml
liveSave = false

# Automatically rerun script when the file is modified on disk.
# Default: false
# The value below was set in H:\.streamlit\config.toml
runOnSave = false